### ISSUE TITLE
New package console

### ISSUE THREAD

**Issue by dodokpeter** [LucciaChia/sudoku-with-tests#36]
This package will have all classes connected to console displaying

**Comment by dodokpeter** [comment]
Methods: display (message), input()

**Comment by andamundale** [comment]
update all tests (and check other classes) to use console package

**Comment by LucciaChia** [comment]
I have problems with System.console() - it returns null for me. Please run Main class and try reproduce this.
According to next article it might be impossible to use console(). 
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206852195-Unable-to-use-java-groovy-console-while-debugging

I've also found multiple suggestions on the internet recomend to avoid using console()

**Comment by dodokpeter** [comment]
> I have problems with System.console() - it returns null for me. Please run Main class and try reproduce this.
> According to next article it might be impossible to use console().
> https://intellij-support.jetbrains.com/hc/en-us/community/posts/206852195-Unable-to-use-java-groovy-console-while-debugging
> 
> I've also found multiple suggestions on the internet recomend to avoid using console()

First test if console != null. if it is not, just use good old method from System.out.

**Comment by LucciaChia** [comment]
Incorrectly pushed also Main class here. It should've been pushed into #38

**Comment by andamundale** [comment]
https://github.com/LucciaChia/sudoku-with-tests/commit/2d903221fe606c0314926f14e713abf584f63675#r33599645
