### ISSUE TITLE
Strategies:    private String name = "0: NackedSingleInACell";

### ISSUE THREAD

**Issue by dodokpeter** [LucciaChia/sudoku-with-tests#40]
0: instead of enum (LOW, MEDIUM, HIGH)
consider moving to console package

**Comment by andamundale** [comment]
TODO consider moving to console package

**Comment by andamundale** [comment]
SudokuLevelType can be defined as the highest strategy type needed/used to solve that particular sudoku

- assign it to sudoku? (it would be highest strategy type used so far)
- assign it to the instance of invoker? that would mean that one invoker is for one sudoku only (I prefer this one)
- different state of the "same" sudoku are different sudokus thus may have different SudokuLevelType
