### ISSUE TITLE
Jococo plugin -80% rule

### ISSUE THREAD

**Issue by dodokpeter** [LucciaChia/sudoku-with-tests#56]
if code coverage<80% -> build failed

**Comment by andamundale** [comment]
Mocking static properties (Scanner and Display in class ConsoleDisplayer) seems to be more difficult than expected. 
Mocking static variables and methods can be done by using PowerMock, but its use with Mockito results in all tests (in class using PowerMock and Mockito) being ignored (there seems to be compatible versions but that did not help). Thus 80% coverage for each package/class is at the moment unachievable.
